-- criar tabelas
CREATE TABLE USUARIO(
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    DATA_NASC DATE,
    GENERO VARCHAR2(25)
)

CREATE TABLE TAREFA(
    ID NUMBER PRIMARY KEY,
    USUARIO_ID NUMBER,
    DESCRICAO VARCHAR2(200),
    DATA_CRIACAO DATE,
    DATA_LIMITE DATE,
    TEMPO_ESTIMADO NUMBER,
    SITUACAO VARCHAR2(25),
    CONSTRAINT FK_TAREFA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID)
)

CREATE TABLE RELATORIO(
    ID NUMBER PRIMARY KEY,
    EXECUTADOS NUMBER,
    PENDENTES NUMBER,
    PERCENTUAL_EXE VARCHAR2(50),
    USUARIO_ID NUMBER,
    CONSTRAINT FK_RELATORIO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID)
)


-- DA TABELA USUARIO
CREATE SEQUENCE USUARIO_SEQ;

CREATE OR REPLACE TRIGGER USUARIO_TRIGGER
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    :NEW.ID := USUARIO_SEQ.NEXTVAL;

    IF (:NEW.NOME IS NULL OR LENGTH(TRIM(:NEW.NOME)) = 0) or (:NEW.EMAIL IS NULL OR LENGTH(TRIM(:NEW.EMAIL)) = 0)
        THEN 
            :NEW.NOME := 'ANONIMO';
            :NEW.EMAIL := 'ANONIMO@MEIL';
            :NEW.DATA_NASC := SYSDATE;
            :NEW.GENERO := 'ANONIMO';
    
    ELSIF (:NEW.DATA_NASC IS NULL OR LENGTH(TRIM(:NEW.DATA_NASC)) = 0) OR (:NEW.GENERO IS NULL OR LENGTH(TRIM(:NEW.GENERO)) = 0)
        THEN
            :NEW.DATA_NASC := SYSDATE;
            :NEW.GENERO := 'ANONIMO';
    END IF;
END;


--DA TABELA TAREFA
CREATE SEQUENCE TAREFA_SEQ

CREATE OR REPLACE TRIGGER TAREFA_TRIGGER
BEFORE INSERT ON TAREFA
FOR EACH ROW
BEGIN
    :NEW.ID := TAREFA_SEQ.NEXTVAL;

    IF :NEW.DESCRICAO IS NULL OR LENGTH(TRIM(:NEW.DESCRICAO)) = 0 
    THEN
        :NEW.USUARIO_ID := 0;
        :NEW.DESCRICAO := NULL;
        :NEW.DATA_CRIACAO := NULL;
        :NEW.DATA_LIMITE := NULL;
        :NEW.TEMPO_ESTIMADO := 0;
        :NEW.SITUACAO := NULL;
    END IF;
END;

INSERT INTO "TAREFA"
(USUARIO_ID, DESCRICAO, DATA_CRIACAO, DATA_LIMITE, TEMPO_ESTIMADO, SITUACAO)
VALUES
(21, '', sysdate, sysdate+1, 2, 'pendente')

SELECT * FROM TAREFA
